"""estrutura inicial com composicao de frete

Revision ID: faa05e1d23e5
Revises: 
Create Date: 2026-06-19 01:14:14.141259
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# identificadores de revisão, usados pelo Alembic.
revision: str = 'faa05e1d23e5'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('empresas',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('razao_social', sa.String(length=200), nullable=False),
    sa.Column('nome_fantasia', sa.String(length=200), nullable=False),
    sa.Column('cnpj_matriz', sa.String(length=20), nullable=False),
    sa.Column('status', sa.String(length=10), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('empresas', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_empresas_cnpj_matriz'), ['cnpj_matriz'], unique=True)

    op.create_table('meta_nacional',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('meta_rs_kg', sa.Float(), nullable=False),
    sa.Column('meta_pct_frete', sa.Float(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('meta_regional',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('macro_regiao', sa.String(length=15), nullable=False),
    sa.Column('meta_rs_kg', sa.Float(), nullable=False),
    sa.Column('meta_pct_frete', sa.Float(), nullable=False),
    sa.Column('prazo_medio_meta', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('meta_regional', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_meta_regional_macro_regiao'), ['macro_regiao'], unique=True)

    op.create_table('regioes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nome', sa.String(length=120), nullable=False),
    sa.Column('descricao', sa.String(length=255), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('nome')
    )
    op.create_table('transportadoras',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('razao_social', sa.String(length=200), nullable=False),
    sa.Column('nome_fantasia', sa.String(length=200), nullable=False),
    sa.Column('cnpj', sa.String(length=20), nullable=False),
    sa.Column('endereco', sa.String(length=200), nullable=False),
    sa.Column('cidade', sa.String(length=120), nullable=False),
    sa.Column('uf', sa.String(length=2), nullable=False),
    sa.Column('cep', sa.String(length=10), nullable=False),
    sa.Column('contato', sa.String(length=120), nullable=False),
    sa.Column('telefone', sa.String(length=30), nullable=False),
    sa.Column('email', sa.String(length=150), nullable=False),
    sa.Column('status', sa.String(length=10), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('transportadoras', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_transportadoras_cnpj'), ['cnpj'], unique=True)

    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nome', sa.String(length=150), nullable=False),
    sa.Column('email', sa.String(length=150), nullable=False),
    sa.Column('hashed_password', sa.String(length=255), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('is_superuser', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_users_email'), ['email'], unique=True)

    op.create_table('cidades',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nome', sa.String(length=120), nullable=False),
    sa.Column('uf', sa.String(length=2), nullable=False),
    sa.Column('regiao_id', sa.Integer(), nullable=True),
    sa.Column('macro_regiao', sa.String(length=15), nullable=True),
    sa.ForeignKeyConstraint(['regiao_id'], ['regioes.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('cidades', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_cidades_nome'), ['nome'], unique=False)
        batch_op.create_index(batch_op.f('ix_cidades_uf'), ['uf'], unique=False)

    op.create_table('ctes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('empresa_id', sa.Integer(), nullable=False),
    sa.Column('transportadora_id', sa.Integer(), nullable=True),
    sa.Column('chave', sa.String(length=50), nullable=False),
    sa.Column('numero', sa.String(length=20), nullable=False),
    sa.Column('serie', sa.String(length=10), nullable=False),
    sa.Column('data_emissao', sa.Date(), nullable=True),
    sa.Column('tomador_cnpj', sa.String(length=20), nullable=False),
    sa.Column('peso', sa.Float(), nullable=False),
    sa.Column('valor_frete', sa.Float(), nullable=False),
    sa.Column('valor_mercadoria', sa.Float(), nullable=False),
    sa.Column('municipio_origem', sa.String(length=120), nullable=False),
    sa.Column('uf_origem', sa.String(length=2), nullable=False),
    sa.Column('municipio_destino', sa.String(length=120), nullable=False),
    sa.Column('uf_destino', sa.String(length=2), nullable=False),
    sa.Column('macro_regiao_destino', sa.String(length=15), nullable=True),
    sa.Column('data_saida', sa.Date(), nullable=True),
    sa.Column('data_entrega', sa.Date(), nullable=True),
    sa.Column('origem_importacao', sa.String(length=10), nullable=False),
    sa.Column('composicao_frete', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['empresa_id'], ['empresas.id'], ),
    sa.ForeignKeyConstraint(['transportadora_id'], ['transportadoras.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('ctes', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_ctes_chave'), ['chave'], unique=True)
        batch_op.create_index(batch_op.f('ix_ctes_empresa_id'), ['empresa_id'], unique=False)

    op.create_table('filiais',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('empresa_id', sa.Integer(), nullable=False),
    sa.Column('razao_social', sa.String(length=200), nullable=False),
    sa.Column('cnpj', sa.String(length=20), nullable=False),
    sa.Column('cidade', sa.String(length=120), nullable=False),
    sa.Column('uf', sa.String(length=2), nullable=False),
    sa.ForeignKeyConstraint(['empresa_id'], ['empresas.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('filiais', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_filiais_cnpj'), ['cnpj'], unique=False)
        batch_op.create_index(batch_op.f('ix_filiais_empresa_id'), ['empresa_id'], unique=False)

    op.create_table('nfes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('cte_id', sa.Integer(), nullable=True),
    sa.Column('chave', sa.String(length=50), nullable=False),
    sa.Column('numero', sa.String(length=20), nullable=False),
    sa.Column('data_emissao', sa.Date(), nullable=True),
    sa.Column('valor_mercadoria', sa.Float(), nullable=False),
    sa.Column('peso', sa.Float(), nullable=False),
    sa.Column('municipio_destino', sa.String(length=120), nullable=False),
    sa.ForeignKeyConstraint(['cte_id'], ['ctes.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('nfes', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_nfes_chave'), ['chave'], unique=False)
        batch_op.create_index(batch_op.f('ix_nfes_cte_id'), ['cte_id'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('nfes', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_nfes_cte_id'))
        batch_op.drop_index(batch_op.f('ix_nfes_chave'))

    op.drop_table('nfes')
    with op.batch_alter_table('filiais', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_filiais_empresa_id'))
        batch_op.drop_index(batch_op.f('ix_filiais_cnpj'))

    op.drop_table('filiais')
    with op.batch_alter_table('ctes', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_ctes_empresa_id'))
        batch_op.drop_index(batch_op.f('ix_ctes_chave'))

    op.drop_table('ctes')
    with op.batch_alter_table('cidades', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_cidades_uf'))
        batch_op.drop_index(batch_op.f('ix_cidades_nome'))

    op.drop_table('cidades')
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_users_email'))

    op.drop_table('users')
    with op.batch_alter_table('transportadoras', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_transportadoras_cnpj'))

    op.drop_table('transportadoras')
    op.drop_table('regioes')
    with op.batch_alter_table('meta_regional', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_meta_regional_macro_regiao'))

    op.drop_table('meta_regional')
    op.drop_table('meta_nacional')
    with op.batch_alter_table('empresas', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_empresas_cnpj_matriz'))

    op.drop_table('empresas')
    # ### end Alembic commands ###
